---
title: "EHM-2022- MLDL"
author: "Loza"
date: '2022-07-11'
output: html_document
---

## Clear environment

```{r env}
rm(list = ls())
```

## Load libraries

```{r lib, warning = FALSE, message = FALSE, results = 'hide'}
library(readxl)
library(mclust)
library(kohonen)
library(deepANN)
```

## Daten laden

Daten vom 08.07.22

```{r data, message=TRUE, warning=TRUE}
library(readr)
df <- read_delim("Desktop/KI-Kultur/EHM_2022/Datenanalyse/data_project_915691_2022_07_11.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
View(df)

# 6. Heatmap
# A heatmap shows the highest and lowest values of specific columns within the grid units. Exploring the heatmaps may help to identify potential clusters.
coolBlueHotRed <- function(n, alpha = 1) { rainbow(n, end = 4 / 6, alpha = alpha)[n:1] }
n <- length(colnames(X))
for (i in 1:n) {
  x_column <- colnames(X)[i]
  plot(som_model, type = "property", property = getCodes(som_model)[, x_column],
       main = paste0("Heatmap: ", x_column), palette.name = coolBlueHotRed)
}
```

## Daten vorverarbeiten

```{r ,warning=TRUE} 
#PLZ auf numeric df$V_609 <- as.numeric(df$V_609)

Swiss <- lapply(df,split.data.frame(df, df$V_609<10000))

length(df$V_609[8])

#Kinder 99 = 0 setzen 
df$V_611[df$V_611 == 99] <- 0

#ALter kleiner 10 ungültig 

df$V_600[df$V_600<= 10| df$V_600 >100] 
df<-df[-36,]

#Matrix mit Merkmalen erstellen
X <- as.matrix(df[, match(c("V_600","V_601", "V_609", "V_610","V_611","V_616","V_617","V_618"), names(df))]) 
colnames(X) <- c("Alter", "Geschlecht", "PLZ", "Familienstand","Kinder","Bildungstand", "Tätigkeit", "Kulturbezug_Beruf")

#X \<- as.matrix(df[, c(which(colnames(df) %in% c("V_600","V_601")))]) 
#colnames(X) \<- c("Alter", "Geschlecht")

#X<- as.numeric(X) 

# Set seed to ensure reproducibility 

set.seed(222)
som_grid <- somgrid(xdim = 5, ydim = 5, topo = "rectangular")
som_model <- som(X, grid = som_grid, alpha = c(0.05, 0.01), radius = 1)

plot(som_model, type = "changes")
plot(som_model, type = "counts")
plot(som_model, type = "mapping")
som_model$unit.classif
table(som_model$unit.classif) # The total number of assigned input samples per each grid unit
plot(som_model, type = "dist.neighbours", main = "SOM neighbour distances")
plot(som_model, type = "quality")
n <- length(colnames(X))
for (i in 1:n) {
  x_column <- colnames(X)[i]
  plot(som_model, type = "property", property = getCodes(som_model)[, x_column],
       main = paste0("Heatmap: ", x_column), palette.name = coolBlueHotRed)
}
plot(som_model, type = "codes", )

# 7. Fan diagram
# Codebook vector spread; a codebook vector is a vector of the weights of the grid units.
getCodes(som_model)
# The size of the fan indicates the height of the value of the corresponding x variable
plot(som_model, type = "codes")
#plot(som_model, type = "codes", palette.name = rainbow, main = "5 by 5 Mapping of Application Data")
```

##Neuro
```{r ,warning=TRUE} 

